[package]
name = "rocket-webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
bon = "3.8"
hex = "0.4"
hmac = "0.12"
rocket = { version = "0.5", features = ["json"] }
sha2 = "0.10"
tokio-util = { version = "0.7", features = ["io"] }
zeroize = "1.8"

[dev-dependencies]
serde = "1.0.228"
