[package]
name = "rocket-webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.8.0"
hex = "0.4.3"
hmac = "0.12"
rocket = { version = "0.5", features = ["json"] }
sha1 = "0.10.6"
sha2 = "0.10"
tokio-util = { version = "0.7", features = ["io"] }
zeroize = "1.8.2"

[dev-dependencies]
serde = "1.0.228"
