name: CI
on:
  push:
    paths:
      - src/**
      - tests/**
      - Cargo.toml
      - Cargo.lock
env:
  RUST_VERSION: 1.90

jobs:
  test:
    name: Test crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ env.RUST_VERSION }} --profile minimal --no-self-update
      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9

      - name: Build tests
        run: cargo build --tests --all-features -p rocket-webhook

      - name: Test crate
        run: cargo nextest run --all-features --profile ci -p rocket-webhook

      - name: Test docs
        run: cargo test --doc --all-features -p rocket-webhook
